env:
  node: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends: 
  - 'eslint:recommended'
overrides:
  - files: ['**/*.ts']
    extends:
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
    rules:
      '@typescript-eslint/indent':
        - error
        - 2
      '@typescript-eslint/no-explicit-any':
        - off
      '@typescript-eslint/no-var-requires':
        - off
      '@typescript-eslint/explicit-function-return-type':
        - error
        - allowExpressions: true
      '@typescript-eslint/no-object-literal-type-assertion':
        - off
      '@typescript-eslint/no-unused-vars':
        - error
        - args: none
      '@typescript-eslint/interface-name-prefix':
        - off
  - files: ['**/*.js']
    rules:
      indent:
        - error
        - 2
      no-unused-vars:
        - error
        - args: none
  - files: ['test/**/*.spec.{j,t}s']
    env:
      jest: true

rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - code: 120
      ignoreUrls: true
  eol-last:
    - error
    - always
  no-trailing-spaces:
    - error
  comma-dangle:
    - error
    - always-multiline
